version: '3.4'

services:
  frontend:
    build: frontend
    restart: always
    env_file:
      - frontend/.env
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
  backend:
    build: backend
    restart: always
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgresql://master:sakjfsdfasfasersfedfsdfa@postgres:5432/master?schema=public
      SITE_ORIGIN: https://sia.watch
      WEBAUTHN_RPID: sia.watch
      REDIS_URL: redis://redis:6379
  postgres:
    image: postgres
    restart: always
    volumes:
      - './database:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: sakjfsdfasfasersfedfsdfa
      POSTGRES_USER: master
      POSTGRES_DATABASE: master
  nginx:
    build: nginx/master
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sia.watch
      PGADMIN_DEFAULT_PASSWORD: somepassword
      PGADMIN_DISABLE_POSTFIX: true
  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_URL: http://nginx:8080
      TUNNEL_TOKEN: your_token_here
