Document: siawatch-app
Title: Debian siawatch-app Manual
Author: <insert document author here>
Abstract: This manual describes what siawatch-app is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/siawatch-app/siawatch-app.sgml.gz

Format: postscript
Files: /usr/share/doc/siawatch-app/siawatch-app.ps.gz

Format: text
Files: /usr/share/doc/siawatch-app/siawatch-app.text.gz

Format: HTML
Index: /usr/share/doc/siawatch-app/html/index.html
Files: /usr/share/doc/siawatch-app/html/*.html
